version: '3.5'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: unless-stopped
    container_name: db_postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=mydatabase
  api:
    container_name: risk-smart-employees
    depends_on: 
      - postgres
    restart: always
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/code/api
    env_file:
      - ./server/.env  
    command: npm run dev
    environment:
      - DATABASE_URL=postgres://postgres:db_password@postgres:5432/mydatabase
#      - DEV_DATABASE_URL=postgres://<db_user>:<db_password>@127.0.0.1:5432/dev_db
#      - DATABASE=postgres
#      - DATABASE_USER=postgres
#      - DATABASE_PASSWORD=db_password
      - SECRET=asdlplplfwfwefwekwself.2342.dawasdq

