version: '3.5'
services:
  postgres:
    container_name: risk-smart-employees-db
    restart: always
    image: postgres:9.6.9
    ports:
     - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    container_name: risk-smart-employees-app
    depends_on: 
      - postgres
    restart: always
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    env_file:
      - ./client/.env  
    command: npm run dev
  api:
    container_name: risk-smart-employees
    depends_on: 
      - postgres
    restart: always
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/code
    env_file:
      - ./server/.env  
    command: npm run server-dev

